branches:
  only:
    - master
    - dev

image: 
  - Visual Studio 2017
  - Ubuntu
  - macos

platform:
  - x64

clone_depth: 5

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  nodejs_version: "12.18.3"

for:
  - 
    matrix:
      only:
        - image: macos
    init:
      - sh: cd $HOME/projects/sete
  - 
    matrix:
      only:
        - image: Ubuntu
    init:
      # Install basic packages in Ubuntu
      - sh: sudo apt-get install -y fakeroot dpkg rpm
  - 
    matrix:
      only:
        - image: Visual Studio 2017
    init:
      # Init (set x64 VC) on Windows
      - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
      
# Install scripts
install:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
  # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -

  # Add Wix to Windows Build Path
  - cmd: dir "c:\Program Files (x86)\WiX Toolset"*
  - cmd: set PATH="c:\Program Files (x86)\WiX Toolset v3.11\bin";%PATH%

  # Get the latest LTS version of Node.js in Windows
  - ps: Install-Product node $env:nodejs_version x64

  # Set NPM in Windows to use Visual Studio 2017 and Python x64
  - cmd: npm config set msvs_version "2017"
  - cmd: npm config set python "C:\\Python27-x64\\pythonw.exe"

  # Get the latest LTS version of Node.js in MAC and Linux
  - sh: nvm install $nodejs_version
  - sh: nvm use $nodejs_version
  
  # Install Yarn
  - sh: npm install yarn
  
  # Install Packages
  - cmd: npm install 
  - sh: npm install --no-optional

  # Webify
  - ps: .\webify.ps1
  - sh: chmod +x webify.sh
  - sh: chmod +x webify_macos.sh

  # Linux Webify
  - sh: echo ${APPVEYOR_BUILD_WORKER_IMAGE}
  - sh: if test ${APPVEYOR_BUILD_WORKER_IMAGE} = "Ubuntu"; then ./webify.sh; fi
  - sh: if test ${APPVEYOR_BUILD_WORKER_IMAGE} = "macOS"; then ./webify_macos.sh; fi
  # Rebuild native packages
  # Install SQLite from Source (Native Module)
  # Previous --target=8.5.2
  # - npm install sqlite3 --build-from-source --runtime=electron --target=11.2.2 --dist-url=https://electronjs.org/headers
  
build_script:
  - cmd: set PATH=C:\projects\sete\node_modules\.bin;%PATH%
  - npm run make

artifacts:
  - path: "\\out\\make\\wix\\x64\\sete.msi"
    name: WinBinaries
  - path: "\\out\\make\\deb\\x64\\sete*"
    name: UbuntuBinaries
  - path: "\\out\\make\\sete*"
    name: MacBinaries


deploy:
  release: SETE-v$(APPVEYOR_REPO_TAG_NAME)
  description: 'AUTOMATIC BUILD'
  provider: GitHub
  draft: true
  auth_token: 
    secure: gx5sdTH7NlaxbamcdboCQP+/+ue/zygB78gyfN9f7R0qIb+ZP7Ap1AFjNqYFELfC
  artifact: WinBinaries, UbuntuBinaries, MacBinaries
  on:
    branch: master
    # APPVEYOR_REPO_TAG: true

# deploy:
#   release: SETE-v$(APPVEYOR_BUILD_VERSION)
#   description: 'SETE v1.0.0'
#   provider: GitHub
#   auth_token: 
#     secure: o9FnGoA7kIQPmz6pI/uzpPbOrolyu2jgAzTVV7Ld6TdbmM3pSh60UR7PU2B9FzpF
#   artifact: WinBinaries
#   on:
#     branch: master                 # release from master branch only

on_finish:
  - cmd: ECHO Exiting...
  - sh: echo Exiting...
  # - sh: export APPVEYOR_SSH_BLOCK=true
  # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
  # - sh: export APPVEYOR_VNC_BLOCK=true
  # - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

